name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  libht:
    runs-on: ubuntu-latest

    env:
        DOCKER_IMG: libht
        COMMANDS: "cd /workspaces/libht && mkdir -p build && cd build && ./configure && make"

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          submodules: 'recursive'
          persist-credentials: false

    - name: Build docker image 
      run: |
        echo Building from dockerfile
        docker build .devcontainer -t $DOCKER_IMG --no-cache --pull

    - name: Build
      run: |
        # Set permissions for Docker mount
        sudo chown -R 1000:1000 .
        # Run test
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/libht $DOCKER_IMG bash --login -c "$COMMANDS"
