name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  libht:
    runs-on: ubuntu-latest

    env:
        DOCKER_IMG: libht

    strategy:
        fail-fast: false
        matrix:
            test: [ basic, uuid ]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          submodules: 'recursive'
          persist-credentials: false

    - name: Build docker image 
      run: |
        echo Building from dockerfile
        docker build .devcontainer -t $DOCKER_IMG --no-cache --pull

    - name: Ownership
      run: |
        # Set permissions for Docker mount
        sudo chown -R 1000:1000 .

    - name: Build
      run: |
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/libht $DOCKER_IMG bash --login -c "cd /workspaces/libht && mkdir -p build && cd build && ../configure --prefix=/usr && make"

    - name: Execute tests
      run: |
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/libht $DOCKER_IMG bash --login -c "cd /workspaces/libht && mkdir -p build && cd build && make '${{ matrix.test }}'.check -k"

    - name: Publish
      run: |
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/libht $DOCKER_IMG bash --login -c "cd /workspaces/libht && mkdir -p build && cd build && make DESTDIR=. install "

    - name: Release
      run: |
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/libht $DOCKER_IMG bash --login -c "cd /workspaces/libht && mkdir -p build && cd build && ls -lah && tar -czf libht.tar.gz usr/ "

    - uses: actions/upload-artifact@v2
      with:
        name: libht
        path: build/libht.tar.gz