name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hash:
    runs-on: ubuntu-latest

    env:
        DOCKER_IMG: hash

    strategy:
        fail-fast: false
        matrix:
            test: [ tests/unittest, tests/code-style, tests/build-all , tests/docs ]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          submodules: 'recursive'
          persist-credentials: false

    - name: Build docker image 
      run: |
        echo Building from dockerfile
        docker build .devcontainer -t $DOCKER_IMG --no-cache --pull
    - name: Execute tests
      run: |
        # Set permissions for Docker mount
        sudo chown -R 1000:1000 .
        # Run test
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces/anubis-os $DOCKER_IMG bash --login -c "cd /workspaces/anubis-os && make -C '${{ matrix.test }}' check -k"
