name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
        DOCKER_IMG: check

    strategy:
        fail-fast: false
        matrix:
            test: [ tools/code-style, tools/doxygen ]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          submodules: 'recursive'
          persist-credentials: false

    - name: Build docker image 
      run: |
        echo Building from dockerfile
        docker build .devcontainer -t $DOCKER_IMG --no-cache --pull

    - name: Execute tests
      run: |
        docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v `pwd`:/workspaces $DOCKER_IMG bash --login -c "cd /workspaces && make -C '${{ matrix.test }}' check -k"
